"""empty message

Revision ID: 3570fbd8f765
Revises: 1ba30fd39de7
Create Date: 2019-03-17 13:27:27.203505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3570fbd8f765'
down_revision = '1ba30fd39de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
